[project]
name = "rag-lof"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "beautifulsoup4>=4.14.0",
    "duckdb>=1.4.0",
    "ipykernel>=6.30.1",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "tdqm>=0.0.1",
]
